### ISSUE TITLE
When there is no "init echoshow", does that mean the camera not supporting RTSP?

### ISSUE THREAD

**Issue by vinh-ttn** [guino/ppsapp-rtsp#36]
I bought this [Kogan camera](https://www.kogan.com/au/buy/kogan-smarterhome-full-hd-indoor-wifi-camera/) since I'm in Australia and they are just Tuya vendors

Device info

`{"devname":"Smart Home Camera","model":"Mini 8S","serialno":"100211700","softwareversion":"4.0.8","hardwareversion":"M8S_A2_V10_F37","firmwareversion":"ppstrong-a3-tuya2_kogan-4.0.8.20210909","identity":"MR2012101100929800","authkey":"uZS13qYuGtgT9x3vLj7AvCMQPaP00000","deviceid":"pp013f1af6a423080000","pid":"aaa","WiFi MAC":"b4:fb:e3:63:XX:XX","ETH MAC":"00:00:00:00:00:00"}`

I followed all the steps until the patch step.
I also enabled ONVIF through found tuya config json, but after reboot, the port is open but there is no media stream from it 
(i.e. empty profiles) so I could not find rtsp link. 

So I proceeded to patch the file, and everything went well until I could not find the "**init echoshow**" line in the file.

Does that mean the device does not support RTSP? 

The ports opening:

```PORT     STATE SERVICE
23/tcp   open  telnet
6668/tcp open  irc
8000/tcp open  http-alt
8080/tcp open  http-proxy
8090/tcp open  opsmessaging```

**Comment by guino** [comment]
@thanh2407hacs What application are you using to test onvif? It has been reported that the onvif implementation is buggy and may not work with some software.

The patching instructions were made for firmware 2.x so it won’t help on 4.x and the changes in 4.x make it too different to write instructions.

I would recommend you try using VLC and RTSP directly:
rtsp://IP:8554/Streaming/Channels/101 and rtsp://IP:8554/Streaming/Channels/102 user admin and password admin (or onvif/device password configured in json file if any).

**Comment by vinh-ttn** [comment]
` would recommend you try using VLC and RTSP directly:
rtsp://IP:8554/Streaming/Channels/101 and rtsp://IP:8554/Streaming/Channels/102 user admin and password admin (or onvif/device password configured in json file if any).`

Thanks alot! Didn't know it's simple like that. Yes the RTSP stream can be viewed at Channel 102 in my case

`rtsp://admin:admin@IP:8554/Streaming/Channels/102`

My deviceInfo on 8090 requires admin:admin to view, so I set the onvif password to admin too. So not sure which "admin" password it was but it works!!!

We'll resolve this issue then! No need to patch. Thanks for your time @guino
