### ISSUE TITLE
Request: ppstrong-c51-tuya2_teco-2.9.2.20191106

### ISSUE THREAD

**Issue by Suspect-byte** [guino/ppsapp-rtsp#4]
Hi @guino,

I am back with another camera. Can you maybe patch the ppsapp?

```
`{"devname":"Smart` Home Camera",
"model":"Bullet 2S",
"serialno":"058960514",
"softwareversion":"2.9.2",
"hardwareversion":"B2S_V10_H1_2063",
"firmwareversion":"ppstrong-c51-tuya2_teco-2.9.2.20191106",
"authkey":"L8eghnyzhgbxkDjWjY7o1jVtvInnmARi",
"deviceid":"pp0136a7872d0cf0d95c",
"identity":"MR1909090400900528",
`"pid":"aaa",`
```
--deleted--

Thanks in advance!

**Comment by guino** [comment]
I should be able to do it today.

**Comment by guino** [comment]
Here's the patch:
https://github.com/guino/ppsapp-rtsp/issues/1#issuecomment-828564836

Let me know if you have any issues (I don't expect any).

**Comment by Suspect-byte** [comment]
@guino Thank you so much for the fast response! 
Cheers!
